// <auto-generated />
namespace Natura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductoEncasaVencimiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductoEncasaVencimiento));
        
        string IMigrationMetadata.Id
        {
            get { return "202104170522009_ProductoEncasa-Vencimiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
